baseURL = 'http://thomasscothamilton.com/'
languageCode = 'en-us'
title = 'Thomas-Scot Hamilton'
theme = 'hugo-theme-m10c'
googleAnalytics = "G-WMDT577B42"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 2
  [[menu.main]]
    identifier = "skills"
    name = "Skills"
    url = "/skills/"
    weight = 3
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 4
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

[params]
  # General information
  author = "Thomas-Scot Hamilton"
  description = "Experienced Staff Software Engineer with expertise in AI/ML infrastructure, internal developer platforms, and scalable cloud solutions."
  # Additional settings
  menu_item_separator = " | "

  # Social links
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/thomasscothamilton"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/thomasscothamilton"
  [[params.social]]
    icon = "brand-patreon"
    name = "Patreon"
    url = "https://www.patreon.com/thomasscothamilton"
  [[params.social]]
    icon = "brand-kofi"
    name = "Ko-fi"
    url = "https://ko-fi.com/thomasscothamilton"
  [[params.social]]
    icon = "envelope"
    name = "Email"
    url = "mailto:thomas.scot.hamilton@gmail.com"

  # Styling configuration
  [params.style]
    favicon = "images/favicon.ico"
    description = "A dashboard inspired by Google Cloud Console."
    fontFamily = "Roboto, sans-serif"
    showSocialIcons = true

#    primaryColor = "#1A73E8"       # Vibrant blue for clickable elements like icons and text
#    accentColor = "#5F6368"        # Neutral gray for less prominent elements
#    secondaryColor = "#BDC1C6"     # Light gray for secondary text and subtext
#    darkestColor = "#202124"       # Very dark gray for the primary background
#    darkColor = "#292A2D"          # Slightly lighter gray for secondary backgrounds (e.g., side navigation)
#    lightColor = "#F1F3F4"         # Light gray for subtle borders and highlights
#    lightestColor = "#FFFFFF"      # Pure white for modals, cards, or elevated surfaces

    primaryColor = "#5F6368"       # Vibrant blue for clickable elements like icons and text
    accentColor = "#FFFFFF"        # Neutral gray for less prominent elements
    secondaryColor = "#BDC1C6"     # Light gray for secondary text and subtext
    darkestColor = "#FFFFFF"       # Very dark gray for the primary background
    darkColor = "#FFFFFF"          # Slightly lighter gray for secondary backgrounds (e.g., side navigation)
    lightColor = "#BDC1C6"         # Light gray for subtle borders and highlights
    lightestColor = "#5F6368"      # Pure white for modals, cards, or elevated surfaces


[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "feed"

[taxonomies]
  tag = "tags"
  category = "categories"
