baseURL = 'http://thomasscothamilton.com/'
languageCode = 'en-us'
title = 'Thomas-Scot Hamilton'
theme = 'hugo-theme-m10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 2
  [[menu.main]]
    identifier = "skills"
    name = "Skills"
    url = "/skills/"
    weight = 3
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "/experience/"
    weight = 4
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5

[params]
  # Styling configuration
  [params.style]
    darkestColor = "#1a1a1a"    # Rich Black
    darkColor = "#2c2c2c"       # Dark Charcoal
    lightColor = "#afbac4"      # Pale Yellow
    lightestColor = "#ffffff"   # White
    primaryColor = "#16a085"    # Teal Green

  # General information
  author = "Thomas-Scot Hamilton"
  description = "Experienced Staff Software Engineer with expertise in AI/ML infrastructure, internal developer platforms, and scalable cloud solutions."

  # Social links
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/thomasscothamilton"
  [[params.social]]
    icon = "brand-linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/thomasscothamilton"
  [[params.social]]
    icon = "envelope"
    name = "Email"
    url = "mailto:thomas.scot.hamilton@gmail.com"

  # Additional settings
  menu_item_separator = " | "

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "feed"

[taxonomies]
  tag = "tags"
  category = "categories"
